export const SWITCH_OPTION = "SWITCH_OPTION";
export const ADD_LABEL_ELEMENT = "ADD_LABEL_ELEMENT";
export const ADD_NEW_LABEL = "ADD_NEW_LABEL";
export const SELECT_LABEL_ELEMENT = "SELECT_LABEL_ELEMENT";
export const SELECT_LABEL = "SELECT_LABEL";